name: topic6
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_auth: ^0.14.0+5
  cloud_firestore: ^0.12.9+4
  firebase_core: ^0.4.5
  provider: ^3.1.0
  flutter_spinkit: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/
